### ISSUE TITLE
jupyterlab-code-formatter

### ISSUE THREAD

**Issue by ryantam626** [jupyterlab-contrib/jupyterlab-contrib.github.io#74] opened 2024-07-13 07:09 UTC
# Target

- The code repository: https://github.com/ryantam626/jupyterlab_code_formatter
- The npm package on npmjs.com (if available): https://www.npmjs.com/package/jupyterlab_code_formatter
- The python package on pypi.org (if available): https://pypi.org/project/jupyterlab-code-formatter/
- The conda-forge recipe on https://github.com/conda-forge (if available): Not maintained by me, so not sure.
- The documentation website (if available): https://ryantam626.github.io/jupyterlab_code_formatter/

# Reason

Haven't got the time to give this project attention for some time now.

# Checklist

- [X] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [X] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [X] I don't care
- [X] The code is available under a Open Source license
- [X] A license file is present in the code repository
- [X] The extension is working on at least JupyterLab 3.x
- [X] The repository contains a README file describing:
  - [X] The provided feature(s)
  - [X] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [X] How to install the extension
  - [ ] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [X] _optional_ The backend code (Python) is tested
- [X] I certify the extension is not using exclusively paid-plan of any commercial service
- [X] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by fcollonval** [comment] 2024-07-13 08:38
Thanks a lot for your great extension and for proposing the transfer @ryantam626 

in order to transfer the extension to this organization, you will need to carry out action on three web services:
- GitHub:
  - [ ] Accept invitation as owner to jupyterlab-contrib organization
  - [ ] [Enable 2FA](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication)
  - [ ] [Transfer the repository to this organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)
- PyPI:
  - easy path:
    - Add me (handle _fcollonval_) as owner of the PyPI project
  - less easy path: 
    - [ ] Have a verified email linked to your PyPI account
    - [ ] Ping us here when it is done to be able to proceed with the next steps
    - [ ] Accept the invitation to the jupyterlab-contrib PyPI organization
    - [ ] [Enable 2FA](https://pypi.org/help/#totp)
    - [ ] Add the package to the organization: https://pypi.org/manage/organization/jupyterlab-contrib/projects/#add-project-to-organization
- NPM:
  - [ ] Accept the invitation to the jlab-contrib NPM organization
  - [ ] [Enable 2FA](https://docs.npmjs.com/configuring-two-factor-authentication)
  - [ ] Ping us here so we can grant you with the proper right to add the package in the organization
  - [ ] Add the package to the _developers_ team: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access
- conda-forge:
   - Nothing to do as you have no rights on the recipe

> Note: for transferring the package, you may be granted extensive rights that will be reduced later on to reduce hacker attack surface.

Don't hesitate to ping me here if you have questions or troubles with the above steps.

**Comment by krassowski** [comment] 2024-07-13 08:48
:tada: cross-referencing https://github.com/ryantam626/jupyterlab_code_formatter/issues/339.

Just to note this down, after the transfer I would like to:
- fixup the CI workflows (remember about new galata workflow)
- consider building against JupyterLab 4.x as 3.x is EOL (to simplify maintenance)
- investigate the settings schema which renders poorly in the Settings Editor UI which might require a breaking change

**Comment by ryantam626** [comment] 2024-07-13 10:45
Hey

- GitHub:
  - [X] Accept invitation as owner to jupyterlab-contrib organization
  - [X] [Enable 2FA](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication)
  - [X] [Transfer the repository to this organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) <- i did this and selected grant access to maintiners, i hope it's correct!
- PyPI:
  - easy path:
    - [X] Add me (handle _fcollonval_) as owner of the PyPI project

- NPM:
  - [X] Accept the invitation to the jlab-contrib NPM organization
  - [X] [Enable 2FA](https://docs.npmjs.com/configuring-two-factor-authentication) <- i do believe npm enforced 2FA ages ago
  - [X] Ping us here so we can grant you with the proper right to add the package in the organization <-- @fcollonval, pinging as requested
  - [ ] Add the package to the _developers_ team: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access <- unsure how to do this, the UI is not very clear

**Comment by fcollonval** [comment] 2024-07-13 17:29
Thanks @ryantam626 for the quick reaction. 

I updated your rights on npm. You should be able to transfer the package now.

**Comment by fcollonval** [comment] 2024-07-13 17:30
Let me know if you have issue with it.

**Comment by ryantam626** [comment] 2024-07-13 18:03
👍 @fcollonval - i think i have done it, the UI is extremely confusing 😓

**Comment by fcollonval** [comment] 2024-07-14 06:56
I can confirm it has been transferred.

Thanks again for helping to quickly move forward on this.

Follow up for myself:
- [ ] Update links in repo
- [ ] Check badges 
- [ ] Check workflows
- [ ] Update org website to add this extension as part of the org

**Comment by krassowski** [comment] 2024-07-14 10:23
https://github.com/jupyterlab-contrib/jupyterlab_code_formatter/pull/346 is ready for review :) I will be AFK until late in the evening.

**Comment by fcollonval** [comment] 2024-07-15 08:12
@ryantam626 I missed that you are linked a personal sponsor account for the project. Is it ok if we remove it?

**Comment by ryantam626** [comment] 2024-07-15 14:03
@fcollonval of course!

**Comment by krassowski** [comment] 2024-07-19 16:09
It looks like we are nearly there! I tried releasing 3.0 (version bump to indicate that Lab 4.x is now required), but run onto a branch protection rule config issue:

![image](https://github.com/user-attachments/assets/3afb426c-18d6-4ac0-9381-5a791174280e)

**Comment by krassowski** [comment] 2024-07-22 14:09
I aligned the branch protection rules to allow admins, It is now failing on PyPI upload step:

```
Fetching PyPI OIDC token...
Fetching PyPI API token...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 121, in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 685, in publish_assets
    lib.publish_assets(
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/lib.py", line 405, in publish_assets
    twine_token = python.get_pypi_token(release_url, python_package_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/python.py", line [157](https://github.com/jupyterlab-contrib/jupyterlab_code_formatter/actions/runs/10042258208/job/27752284026#step:4:160), in get_pypi_token
    return fetch_pypi_api_token()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/python.py", line 140, in fetch_pypi_api_token
    r.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://pypi.org/_/oidc/github/mint-token
```

Does it ring any bells @fcollonval?

**Comment by fcollonval** [comment] 2024-07-22 14:12
I did not set up the release workflow on pypi 😅 if you want to do it:
https://pypi.org/manage/project/jupyterlab-code-formatter/settings/publishing/

**Comment by krassowski** [comment] 2024-07-22 14:30
Thanks! I populated the form, uploaded artifacts manually and undrafted the GitHub release. We can test the workflow next time. Anything else to do before we close this issue?

**Comment by fcollonval** [comment] 2024-07-29 08:59
No I think we are good --> closing this issue 

Big thanks again to @ryantam626 to allow this great extension to move in this organization.

**Closed by fcollonval** 2024-07-29 08:59 UTC
Labels: transfer

**Comment by ryantam626** [comment] 2024-07-29 10:03
well it's me that should be thanking you guys for your hard work 😸 - Thank you!
